export const sample_foods = [
    {
    id: '1',
    name: 'veg momos',
    cookTime: '10-12',
    price: 199,
    favorite: false,
    origins:['china'],
    stars:4.9,
    imageUrl:"food-1.jpg",
    tags:['FastFood', 'Lunch', 'momos'],
},
{
    id: '2',
    name:'Cheezy pizza',
    cookTime:'15-20',
    price:299,
    favorite:true,
    origins:['Usa', 'russia' ,'europe'],
    stars:4.8,
    imageUrl:'food-2.jpg',
    tags: ['Lunch','FastFood','Pizza'],
},
{
    id:  '3',
    name: 'Burger',
    cookTime:'10-15',
    price:299,
    favorite:false,
    origins:['Germany','italy'],
    stars:4.9,
    imageUrl:'food-3.jpg',
    tags:['FastFood','Burger'],
},
{
    id: '4',
    name:'coffee',
    cookTime:'5-10',
    price: 199,
    favorite: true,
    origins:['us', 'india'],
    stars:5.0,
    imageUrl:'food-4.jpg',
    tags:['coffee','Drinks','Dinner']
},
{
    id:'5',
    name:'Chicken Burger',
    price:199,
    cookTime:'30-35',
    favorite:false,
    origins:['Uk',' ','france'],
    stars:4.8,
    imageUrl:'food-5.jpg',
    tags:['Burger','FastFood']

},
{
    id:'6',
    name:'veg-pizza',
    cookTime:'10-20',
    price:399,
    favorite:false,
    origins:['Purtogal','Norway','Denmark'],
    stars:4.6,
    imageUrl:'food-6.jpg',
    tags: ['Lunch','Dinner','Pizza',]
},
{
    id:'7',
    name:'Hakka Noodles',
    cookTime:'8-10',
    price:299,
    favorite:false,
    origins:['China','korea'],
    stars:4.5,
    imageUrl:'food-7.jpg',
    tags: ['FastFood','Lunch']
},
{
    id:'8',
    name:'Fried Rice',
    cookTime:'10-15',
    price:149,
    favorite:false,
    origins:['India','Canada'],
    stars:4.5,
    imageUrl:'food-8.jpg',
    tags: ['Lunch','Dinner',]
},
{
    id: '9',
    name: 'Idli Sambhar',
    cookTime: '10-15',
    price: 149,
    favorite: true,
    origins:['South India','India'],
    stars:4.9,
    imageUrl:"food-9.jpg",
    tags:['Breakfast', 'Lunch', 'Dinner'],
},
{
    id: '10',
    name: 'Fish Curry',
    cookTime: '10-12',
    price: 299,
    favorite: false,
    origins:['china','Korea'],
    stars:4.9,
    imageUrl:"food-10.jpg",
    tags:['Lunch','Nonveg'],
},
{
    id: '11',
    name: 'Cocktail',
    cookTime: '10-12',
    price: 199,
    favorite: false,
    origins:['Usa','German'],
    stars:4.9,
    imageUrl:"food-11.jpg",
    tags:['Drinks'],
},
{
    id: '12',
    name: 'Dosa',
    cookTime: '10-12',
    price: 149,
    favorite: false,
    origins:['South India'],
    stars:4.9,
    imageUrl:"food-12.jpg",
    tags:['Breakfast', 'Lunch', 'Dinner'],
},
{
    id: '13',
    name: 'Chicken Rise',
    cookTime: '10-12',
    price: 199,
    favorite: false,
    origins:['South India','East India'],
    stars:4.1,
    imageUrl:"food-13.jpg",
    tags:['Lunch', 'Dinner'],
},
{
    id: '14',
    name: 'Simple thalli',
    cookTime: '10-12',
    price: 99,
    favorite: false,
    origins:['India','North India'],
    stars:4.9,
    imageUrl:"food-14.jpg",
    tags:['Lunch','Breakfast'],
},
{
    id: '15',
    name: 'Special thalli',
    cookTime: '10-15',
    price: 149,
    favorite: true,
    origins:['India','North India'],
    stars:4.9,
    imageUrl:"food-15.jpg",
    tags:['Lunch', 'Dinner'],
},
{
    id: '16',
    name: 'Chocolate Cake',
    cookTime: '10-12',
    price: 199,
    favorite: false,
    origins:['Russia','china'],
    stars:4.9,
    imageUrl:"food-16.jpg",
    tags:['Sweets'],
},
{
    id: '17',
    name: 'Masala pao',
    cookTime: '10-12',
    price: 99,
    favorite: false,
    origins:['Mumbai'],
    stars:4.9,
    imageUrl:"food-17.jpg",
    tags:['FastFood'],
},
{
    id: '18',
    name: 'Nonveg thalli',
    cookTime: '10-12',
    price: 249,
    favorite: true,
    origins:['India','Uk'],
    stars:4.3,
    imageUrl:"food-18.jpg",
    tags:['Lunch', 'Dinner'],
},
{
    id: '19',
    name: 'Biryani',
    cookTime: '10-15',
    price: 199,
    favorite: false,
    origins:['India'],
    stars:4.9,
    imageUrl:"food-19.jpg",
    tags:['Dinner'],
},
{
    id: '20',
    name: 'Masala Tea',
    cookTime: '10-12',
    price: 59,
    favorite: false,
    origins:['India','china'],
    stars:4.9,
    imageUrl:"food-20.jpg",
    tags:['Drinks'],
},
{
    id: '21',
    name: 'Oreo Shake',
    cookTime: '10-12',
    price: 199,
    favorite: true,
    origins:['India','Canada'],
    stars:4.4,
    imageUrl:"food-21.jpg",
    tags:['Drinks'],
},
{
    id: '22',
    name: 'Tea',
    cookTime: '5-10',
    price: 50,
    favorite: false,
    origins:['India','china','Japan'],
    stars:4.1,
    imageUrl:"food-22.jpg",
    tags:['Drinks',],
},
{
    id: '23',
    name: 'Egg Rice',
    cookTime: '10-12',
    price: 199,
    favorite: false,
    origins:['china','India','Russia'],
    stars:4.9,
    imageUrl:"food-23.jpg",
    tags:['Breakfast'],
},
{
    id: '24',
    name: 'Choco lava cake',
    cookTime: '10-12',
    price: 149,
    favorite: true,
    origins:['Usa','Uk'],
    stars:4.9,
    imageUrl:"food-24.jpg",
    tags:['Sweets', 'Lunch', 'Dinner'],
},
{
    id: '25',
    name: 'Salad',
    cookTime: '10-12',
    price: 149,
    favorite: false,
    origins:['Usa','china','India'],
    stars:4.5,
    imageUrl:"food-25.jpg",
    tags:[ 'Lunch', 'Dinner'],
},
{
    id: '26',
    name: 'Chana Rise',
    cookTime: '10-12',
    price: 99,
    favorite: false,
    origins:['china'],
    stars:4.3,
    imageUrl:"food-26.jpg",
    tags:['Breakfast', 'Dinner'],
},
{
    id: '27',
    name: 'veg thalli',
    cookTime: '10-12',
    price: 149,
    favorite: false,
    origins:['India'],
    stars:4.2,
    imageUrl:"food-27.jpg",
    tags:['Lunch', 'Dinner'],
},
{
    id: '28',
    name: 'pao bhaji',
    cookTime: '10-15',
    price: 99,
    favorite: false,
    origins:['India'],
    stars:4.2,
    imageUrl:"food-28.jpg",
    tags:['FastFood', 'Lunch', 'Dinner'],
},
];



export const sample_tags = [
    {name:"All",count:28},
    {name:"BreakFast",count:5},
    {name:"FastFood",count:5},
    {name:"Pizza",count:2},
    {name:"Lunch",count:15},
    {name:"Dinner",count:10},
    {name:"Drinks",count:5},
    {name:"Burger",count:2},
];

export const sample_users = [
    {
        id: 1,
        name: 'Rahul Rana',
        email: 'Rahul@gmail.com',
        password: '12345',
        address: 'Una Hp',
        isAdmin: false,
    },
    {
        id: 2,
        name: 'Rohit Rana',
        email: 'Rohit@gmail.com',
        password: '12345',
        address: 'Jabalpur',
        isAdmin: true,  
    },
];